/** Utils **/
export const FLASH_MESSAGE = "FLASH_MESSAGE"

/** ROLES **/
export const REQUEST_ROLES = "REQUEST_ROLES"
export const RECEIVE_ROLES = "RECEIVE_ROLES"

/** Estados publicaciones **/
export const REQUEST_PUBLICATION_STATES = "REQUEST_PUBLICATION_STATES"
export const RECEIVE_PUBLICATION_STATES = "RECEIVE_PUBLICATION_STATES"

/** Tipos de congresos **/
export const REQUEST_CONGRESS_TYPES = "REQUEST_CONGRESS_TYPES"
export const RECEIVE_CONGRESS_TYPES = "RECEIVE_CONGRESS_TYPES"

// export const FETCH_ROLES = "FETCH_ROLES"

/** SESIONES **/
export const REQUEST_LOGIN = "REQUEST_LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const REQUEST_LOGOUT = "REQUEST_LOGOUT"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_ERROR = "LOGOUT_ERROR"

export const SET_SESSION_DATA = "SET_SESSION_DATA"

/** Investigadores */
export const EDIT_RESEARCHER = "EDIT_RESEARCHER"
export const UPDATE_RESEARCHER = "UPDATE_RESEARCHER"
export const SHOW_ALL_RESEARCHERS = "SHOW_ALL_RESEARCHERS"
export const SHOW_RESEARCHER = "SHOW_RESEARCHER"

export const REQUEST_RESEARCHERS = "REQUEST_RESEARCHERS"
export const FETCH_RESEARCHERS = "FETCH_RESEARCHERS"
export const RECEIVE_RESEARCHERS = "RECEIVE_RESEARCHERS"

export const REQUEST_RESEARCHER = "REQUEST_RESEARCHER"
export const FETCH_RESEARCHER = "FETCH_RESEARCHER"
export const RECEIVE_RESEARCHER = "RECEIVE_RESEARCHER"

export const REQUEST_ADD_RESEARCHER = "REQUEST_ADD_RESEARCHER"
export const ADD_RESEARCHER_SUCCESS = "ADD_RESEARCHER_SUCCESS"
export const ADD_RESEARCHER_ERROR = "ADD_RESEARCHER_ERROR"

export const REQUEST_UPDATE_RESEARCHER = "REQUEST_UPDATE_RESEARCHER"
export const UPDATE_RESEARCHER_SUCCESS = "UPDATE_RESEARCHER_SUCCESS"
export const UPDATE_RESEARCHER_ERROR = "UPDATE_RESEARCHER_ERROR"

export const REQUEST_DELETE_RESEARCHER = "DELETE_RESEARCHER_REQUEST"
export const DELETE_RESEARCHER_SUCCESS = "DELETE_RESEARCHER_SUCCESS"
export const DELETE_RESEARCHER_ERROR = "DELETE_RESEARCHER_ERROR"

/** AUTORES **/

// fetch
export const REQUEST_AUTHORS = "FETCH_AUTHORS"
export const RECEIVE_AUTHORS = "RECEIVE_AUTHORS"
// add
export const REQUEST_ADD_AUTHOR = "REQUEST_ADD_AUTHOR"
export const ADD_AUTHOR_SUCCESS = "ADD_AUTHOR_SUCCESS"
export const ADD_AUTHOR_ERROR = "ADD_AUTHOR_ERROR"

/** PROYECTOS **/
export const EDIT_PROJECT = "EDIT_PROJECT"
export const UPDATE_PROJECT = "UPDATE_PROJECT"
export const SHOW_ALL_PROJECTS = "SHOW_ALL_PROJECTS"
export const SHOW_PROJECT = "SHOW_PROJECT"

export const REQUEST_PROJECTS = "REQUEST_PROJECTS"
export const FETCH_PROJECTS = "FETCH_PROJECTS"
export const RECEIVE_PROJECTS = "RECEIVE_PROJECTS"

export const REQUEST_PROJECT = "REQUEST_PROJECT"
export const FETCH_PROJECT = "FETCH_PROJECT"
export const RECEIVE_PROJECT = "RECEIVE_PROJECT"

export const REQUEST_ADD_PROJECT = "REQUEST_ADD_PROJECT"
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS"
export const ADD_PROJECT_ERROR = "ADD_PROJECT_ERROR"

export const REQUEST_UPDATE_PROJECT = "REQUEST_UPDATE_PROJECT"
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS"
export const UPDATE_PROJECT_ERROR = "UPDATE_PROJECT_ERROR"

export const REQUEST_DELETE_PROJECT = "DELETE_PROJECT_REQUEST"
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS"
export const DELETE_PROJECT_ERROR = "DELETE_CONGRESS_ERROR"

export const ADD_AUTHOR_TO_CURRENT_PROJECT = "ADD_AUTHOR_TO_CURRENT_PROJECT"
export const EDIT_AUTHOR_FROM_CURRENT_PROJECT = "EDIT_AUTHOR_FROM_CURRENT_PROJECT"
export const DELETE_AUTHOR_FROM_CURRENT_PROJECT = "DELETE_AUTHOR_FROM_CURRENT_PROJECT"

/** AUTORES PROYECTOS **/
export const REQUEST_AUTHORS_PROJECTS = "REQUEST_AUTHORS_PROJECTS"
export const RECEIVE_AUTHORS_PROJECTS = "RECEIVE_AUTHORS_PROJECTS"
export const AUTHORS_PROJECT_NORMALIZED = "AUTHORS_PROJECT_NORMALIZED"

/** CONGRESOS **/
export const EDIT_CONGRESS = "EDIT_CONGRESS"
export const UPDATE_CONGRESS = "UPDATE_CONGRESS"
export const SHOW_ALL_CONGRESSES = "SHOW_ALL_CONGRESSES"
export const SHOW_CONGRESS = "SHOW_CONGRESS"

export const REQUEST_CONGRESSES = "REQUEST_CONGRESSES"
export const FETCH_CONGRESSES = "FETCH_CONGRESSES"
export const RECEIVE_CONGRESSES = "RECEIVE_CONGRESSES"

export const REQUEST_CONGRESS = "REQUEST_CONGRESS"
export const FETCH_CONGRESS = "FETCH_CONGRESS"
export const RECEIVE_CONGRESS = "RECEIVE_CONGRESS"

export const REQUEST_ADD_CONGRESS = "REQUEST_ADD_CONGRESS"
export const ADD_CONGRESS_SUCCESS = "ADD_CONGRESS_SUCCESS"
export const ADD_CONGRESS_ERROR = "ADD_CONGRESS_ERROR"

export const REQUEST_UPDATE_CONGRESS = "REQUEST_UPDATE_CONGRESS"
export const UPDATE_CONGRESS_SUCCESS = "UPDATE_CONGRESS_SUCCESS"
export const UPDATE_CONGRESS_ERROR = "UPDATE_CONGRESS_ERROR"

export const REQUEST_DELETE_CONGRESS = "DELETE_CONGRESS_REQUEST"
export const DELETE_CONGRESS_SUCCESS = "DELETE_CONGRESS_SUCCESS"
export const DELETE_CONGRESS_ERROR = "DELETE_CONGRESS_ERROR"
