/** Utils **/
export const FLASH_MESSAGE = "FLASH_MESSAGE"

/** Investigadores */
export const EDIT_RESEARCHER = "EDIT_RESEARCHER"
export const UPDATE_RESEARCHER = "UPDATE_RESEARCHER"
export const SHOW_ALL_RESEARCHERS = "SHOW_ALL_RESEARCHERS"
export const SHOW_RESEARCHER = "SHOW_RESEARCHER"

export const REQUEST_RESEARCHERS = "REQUEST_RESEARCHERS"
export const FETCH_RESEARCHERS = "FETCH_RESEARCHERS"
export const RECEIVE_RESEARCHERS = "RECEIVE_RESEARCHERS"

export const REQUEST_RESEARCHER = "REQUEST_RESEARCHER"
export const FETCH_RESEARCHER = "FETCH_RESEARCHER"
export const RECEIVE_RESEARCHER = "RECEIVE_RESEARCHER"

export const REQUEST_ADD_RESEARCHER = "REQUEST_ADD_RESEARCHER"
export const ADD_RESEARCHER_SUCCESS = "ADD_RESEARCHER_SUCCESS"
export const ADD_RESEARCHER_ERROR = "ADD_RESEARCHER_ERROR"

export const REQUEST_UPDATE_RESEARCHER = "REQUEST_ADD_RESEARCHER"
export const UPDATE_RESEARCHER_SUCCESS = "ADD_RESEARCHER_SUCCESS"
export const UPDATE_RESEARCHER_ERROR = "ADD_RESEARCHER_ERROR"

export const REQUEST_DELETE_RESEARCHER = "DELETE_RESEARCHER_REQUEST"
export const DELETE_RESEARCHER_SUCCESS = "DELETE_RESEARCHER_SUCCESS"
export const DELETE_RESEARCHER_ERROR = "DELETE_RESEARCHER_ERROR"

/** SESIONES **/
export const REQUEST_LOGIN = "REQUEST_LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const REQUEST_LOGOUT = "REQUEST_LOGOUT"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_ERROR = "LOGOUT_ERROR"
