export const ADD_RESEARCHER = "ADD_RESEARCHER"
export const UPDATE_RESEARCHER = "UPDATE_RESEARCHER"
export const DELETE_RESEARCHER = "DELETE_RESEARCHER"
export const SHOW_ALL_RESEARCHERS = "SHOW_ALL_RESEARCHERS"
export const SHOW_RESEARCHER = "SHOW_RESEARCHER"

export const FETCH_RESEARCHERS = "FETCH_RESEARCHERS"
